CREATE OR REPLACE TABLE pse_ak (
    id INT NOT NULL AUTO_INCREMENT,
    isin VARCHAR(12),
    name VARCHAR(18),
    bic VARCHAR(8),
    `date` date,
    price_closing FLOAT(13,2),
    price_change FLOAT(7,2),
    price_previous FLOAT(13,2),
    price_yearly_min FLOAT(13,2),
    price_yearly_max FLOAT(13,2),
    count_of_securities FLOAT(11,0),
    volume_of_deals FLOAT(17,2),
    last_deal_date date,
    business_group VARCHAR(1),
    trading_mode VARCHAR(1),
    market_code VARCHAR(1),
    price_daily_min FLOAT(13,2),
    price_daily_max FLOAT(13,2),
    price_opening FLOAT(13,2),
    lot_size FLOAT(5,0),
    PRIMARY KEY(id)
);

CREATE OR REPLACE TABLE cnb_er (
    id INT NOT NULL AUTO_INCREMENT,
    `date` date NOT NULL,
    AUD FLOAT(7,3),
    BGN FLOAT(7,3),
    BRL FLOAT(7,3),
    CAD FLOAT(7,3),    
    CHF FLOAT(7,3),    
    CNY FLOAT(7,3),    
    DKK FLOAT(7,3),    
    EUR FLOAT(7,3),    
    GBP FLOAT(7,3),
    HKD FLOAT(7,3),
    HRK FLOAT(7,3),
    HUF100 FLOAT(7,3),
    IDR1000 FLOAT(7,3),
    ILS FLOAT(7,3),
    INR100 FLOAT(7,3),
    ISK100 FLOAT(7,3),  
    JPY100 FLOAT(7,3),
    KRW100 FLOAT(7,3),
    MXN FLOAT(7,3),
    MYR FLOAT(7,3),
    NOK FLOAT(7,3),
    NZD FLOAT(7,3),
    PHP100 FLOAT(7,3),
    PLN FLOAT(7,3),
    RON FLOAT(7,3),
    RUB100 FLOAT(7,3),
    SEK FLOAT(7,3),
    SGD FLOAT(7,3),
    THB100 FLOAT(7,3),
    TRY FLOAT(7,3),
    USD FLOAT(7,3),
    XDR FLOAT(7,3),
    ZAR FLOAT(7,3),
    PRIMARY KEY(id)
);
